"""Write DICTIONARIES.md: the recommended dictionaries, from the files the build itself reads.

    python3 scripts/recommended_doc.py            # rewrite DICTIONARIES.md
    python3 scripts/recommended_doc.py --check    # exit 1 if it is out of date

The source is site/data/recommended.json (data/recommended.json resolved by build_site.py to
record ids) and site/data/dicts.json, the same pair scripts/fetch_corpus.py downloads from: each
pick's record, and its first location, the most complete copy. tests/test_recommended_doc.py fails
when the committed file differs from what this writes.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "DICTIONARIES.md"
STATUS = {  # the labels the site shows (site/view.js)
    "current": "current: the newest edition",
    "behind": "behind: a newer edition exists, not on freemdict",
    "snapshot": "snapshot: a dated copy of a work updated online",
    "final": "final: the last edition there will be",
    "unclear": "unclear: the copy's edition cannot be told",
    "missing": "missing: not on freemdict",
}


def _gb(size: int) -> str:
    return f"{size / 1e9:.2f} GB" if size >= 1e8 else f"{size / 1e6:.0f} MB"


def render(resolved: dict, dicts: list[dict]) -> str:
    by_id = {d["id"]: d for d in dicts}
    rows, total, picked = [], 0, 0
    for cat in resolved["categories"]:
        rows.append(f"\n## {cat['en']} · {cat['zh']}\n")
        rows.append("| Key | Dictionary | Newest edition | Copy on freemdict | Status | Files |")
        rows.append("|---|---|---|---|---|---|")
        for item in cat["items"]:
            name = item["full"] + (f" · {item['zh']}" if item.get("zh") else "")
            if item.get("starter"):
                name += " ★"
            record = by_id.get(item.get("id"))
            if record is None:
                copy, files = "—", "—"
            else:
                loc = record["loc"][0]
                size = sum(s for _, s in loc["f"])
                total += size
                picked += 1
                copy = f"{record['n']} (`{loc['p']}`)"
                files = f"{len(loc['f'])}, {_gb(size)}"
            latest = f"[{item['latest']}]({item['src']})"
            rows.append(f"| `{item['key']}` | {name} | {latest} | {copy} | {item['status']} | {files} |")
    status_lines = "\n".join(f"- {text}" for text in STATUS.values())
    return f"""# Recommended dictionaries

Generated by `scripts/recommended_doc.py` from `data/recommended.json` (edited by hand,
reviewed {resolved['reviewed']}) and the crawled index; do not edit this file, edit the JSON and
run the script. These are the dictionaries the site recommends and the ones
`scripts/fetch_corpus.py` downloads and the local database is built from: {picked} with a copy on
freemdict, {_gb(total)} in all. ★ marks the starter set the site shows first.

"Copy on freemdict" is the record the build downloads, and the folder of its most complete copy.
"Newest edition" links to the source that says what the newest edition is. Status:

{status_lines}
{chr(10).join(rows)}

Each key with a copy has a parser in `scripts/structured/parsers/` that reads it into the shared
model (`READING.md` says what the built database holds and how to read it). A dictionary with no
copy on freemdict is listed so its absence is on record; it is not built.
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if DICTIONARIES.md is out of date")
    args = ap.parse_args()
    text = render(json.loads((ROOT / "site/data/recommended.json").read_text(encoding="utf-8")),
                  json.loads((ROOT / "site/data/dicts.json").read_text(encoding="utf-8")))
    if args.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            sys.exit("DICTIONARIES.md is out of date: run python3 scripts/recommended_doc.py")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}", file=sys.stderr)


if __name__ == "__main__":
    main()
